# ==========================================
# INTERNAL KUBERNETES SERVICES
# ==========================================
# This file creates the internal DNS records for all microservices.
# For example, to call the Auth Service, you just make an HTTP request to http://auth-service:8001

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: terminal-service
spec:
  selector:
    app: terminal
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Nginx exposes port 80 by default inside the container
      targetPort: 80
